version: '3'

env:
  ADB_SERVER_SOCKET: tcp:$(cat /etc/resolv.conf | awk '/nameserver/ {print $2}'):5037

tasks:
  proxy:
    dotenv: ['.env.local']
    cmds:
      - node_modules/.bin/nodemon dev-api-proxy.js

  apk:
    cmds:
      - eas build --platform android --local --profile preview --output ha-shopping.apk
  
  devbuild:
    cmds:
      - eas build --platform android --local --profile development --output ha-shopping.apk
  
  install:
    cmds:
      - adb install ha-shopping.apk

  devices:
    cmds:
    - adb devices